##############################################################################
# FILE FORMAT FUZZING SETTINGS
##############################################################################
orig_path: C:\Users\Tribal\Documents\Visual Studio 2015\Projects\Fuzzer_Framework_Git\Fuzzer_Framework\original
mutated_path: C:\Users\Tribal\Documents\Visual Studio 2015\Projects\Fuzzer_Framework_Git\Fuzzer_Framework\mutated
result_path: C:\Program Files (x86)

target_program: C:\Users\Tribal\Documents\Visual Studio 2015\Projects\Hello\Debug\Hello.exe
program_option: 

timeout: 5
test_count: 5
dummy_size: 1000

##############################################################################
# RDP PROTOCOL FUZZING SETTINGS
##############################################################################
server_ip: 192.168.52.128
port: 3389
domain: 
username: Administrator
password: 1234
command: 
directory: 
server_rdp_version: 4
